// ─── Mockup Fidelity Tests ───────────────────────────────────────────────────
// Compares per-component mockup fragment HTML against the corresponding
// Storybook story using pixelmatch. The mockup fragments are the source of
// truth for what each component SHOULD look like.
//
// Fragments are generated by: node scripts/generate-mockup-fragments.mjs
// and placed in dist/storybook/mockup-fragments/{story-id}.html
//
// Run:  pnpm test:storybook-visual (includes this file)
//
// Diff images saved to test-debug/fidelity/ on every run for inspection.

import fs from "node:fs";
import path from "node:path";
import { expect, test } from "@playwright/test";
import pixelmatch from "pixelmatch";
import { PNG } from "pngjs";

// ─── Configuration ──────────────────────────────────────────────────────────

/** Maximum allowed pixel diff ratio (0-1). Tighten as components converge. */
/**
 * Maximum allowed diff ratio between mockup fragment and Storybook story.
 * 0.025 (2.5%) allows for anti-aliasing, font rendering, and animation
 * frame timing differences while catching any meaningful visual divergence.
 */
const MAX_DIFF_RATIO = 0.025;

const DEBUG_DIR = path.resolve(
	import.meta.dirname,
	"../../test-debug/fidelity",
);

// ─── Pairs: each maps a mockup fragment to its Storybook story ──────────────

interface FidelityPair {
	name: string;
	storyId: string;
	/** Override max diff for this pair */
	maxDiff?: number;
}

const PAIRS: FidelityPair[] = [
	// ─── Chat components ─────────────────────────────────────────
	{ name: "UserMessage", storyId: "chat-usermessage--default" },
	{ name: "ThinkingBlock Active", storyId: "chat-thinkingblock--active" },
	{ name: "ThinkingBlock Completed", storyId: "chat-thinkingblock--completed" },

	// Tool items — standalone
	{ name: "ToolItem Completed", storyId: "chat-toolitem--completed" },
	{ name: "ToolItem Running", storyId: "chat-toolitem--running" },
	{ name: "ToolItem Error", storyId: "chat-toolitem--error-state" },
	{ name: "ToolItem Pending", storyId: "chat-toolitem--pending" },

	// Tool items — grouped
	{ name: "ToolItem First In Group", storyId: "chat-toolitem--first-in-group" },
	{
		name: "ToolItem Middle Of Group",
		storyId: "chat-toolitem--middle-of-group",
	},
	{ name: "ToolItem Last In Group", storyId: "chat-toolitem--last-in-group" },

	// Tool items — question variants
	{
		name: "ToolItem Question Running",
		storyId: "chat-toolitem--question-running",
	},
	{
		name: "ToolItem Question Answered",
		storyId: "chat-toolitem--question-answered",
	},

	// Result bar
	{ name: "ResultBar Full", storyId: "chat-resultbar--full" },

	// ─── Session items ───────────────────────────────────────────
	{ name: "SessionItem Active", storyId: "session-sessionitem--active" },
	{ name: "SessionItem Inactive", storyId: "session-sessionitem--inactive" },
	{
		name: "SessionItem Processing",
		storyId: "session-sessionitem--processing",
	},

	// ─── Permissions ────────────────────────────────────────────
	{
		name: "PermissionCard Pending",
		storyId: "permissions-permissioncard--pending",
	},

	// ─── Layout ──────────────────────────────────────────────────
	{ name: "Header Connected", storyId: "layout-header--connected" },
	{ name: "Header Disconnected", storyId: "layout-header--disconnected" },
	{ name: "Header Processing", storyId: "layout-header--processing" },

	// ─── Input ───────────────────────────────────────────────────
	{ name: "InputArea Empty", storyId: "input-inputarea--empty" },
	{ name: "InputArea Processing", storyId: "input-inputarea--processing" },
	{
		name: "InputArea Context Bar",
		storyId: "input-inputarea--with-context-bar",
	},
	{ name: "InputArea High Context", storyId: "input-inputarea--high-context" },
	{
		name: "InputArea Critical Context",
		storyId: "input-inputarea--critical-context",
	},

	// ─── Overlays ────────────────────────────────────────────────
	{
		name: "ConnectOverlay Connecting",
		storyId: "overlays-connectoverlay--connecting",
	},
];

// ─── Helpers ────────────────────────────────────────────────────────────────

async function freezeAnimations(
	page: import("@playwright/test").Page,
): Promise<void> {
	await page.addStyleTag({
		content: `*, *::before, *::after {
			animation-delay: -0.0001s !important;
			animation-duration: 0s !important;
			animation-play-state: paused !important;
			transition-duration: 0s !important;
			transition-delay: 0s !important;
			caret-color: transparent !important;
		}`,
	});
	await page.waitForTimeout(50);
}

function compareImages(
	imageA: Buffer,
	imageB: Buffer,
	threshold = 0.1,
): { diffCount: number; diffRatio: number; diffImage: Buffer } {
	const pngA = PNG.sync.read(imageA);
	const pngB = PNG.sync.read(imageB);
	const width = Math.min(pngA.width, pngB.width);
	const height = Math.min(pngA.height, pngB.height);

	function cropData(png: PNG, w: number, h: number): Buffer {
		if (png.width === w && png.height === h)
			return png.data as unknown as Buffer;
		const out = Buffer.alloc(w * h * 4);
		for (let y = 0; y < h; y++) {
			const src = y * png.width * 4;
			const dst = y * w * 4;
			png.data.copy(out, dst, src, src + w * 4);
		}
		return out;
	}

	const dataA = cropData(pngA, width, height);
	const dataB = cropData(pngB, width, height);
	const diffPng = new PNG({ width, height });

	const diffCount = pixelmatch(dataA, dataB, diffPng.data, width, height, {
		threshold,
		includeAA: false,
	});

	return {
		diffCount,
		diffRatio: width * height > 0 ? diffCount / (width * height) : 0,
		diffImage: PNG.sync.write(diffPng),
	};
}

function saveDebugImage(name: string, buffer: Buffer): void {
	fs.mkdirSync(DEBUG_DIR, { recursive: true });
	fs.writeFileSync(path.join(DEBUG_DIR, name), buffer);
}

// ─── Tests ──────────────────────────────────────────────────────────────────

test.describe("Mockup Fidelity", () => {
	for (const pair of PAIRS) {
		test(pair.name, async ({ page, context }) => {
			const fragmentUrl = `/mockup-fragments/${pair.storyId}.html`;

			// 1. Screenshot the mockup fragment
			const fragmentResp = await page.goto(fragmentUrl, {
				waitUntil: "domcontentloaded",
			});
			if (!fragmentResp || fragmentResp.status() >= 400) {
				test.skip(
					true,
					`Fragment ${pair.storyId}.html not found (HTTP ${fragmentResp?.status()})`,
				);
				return;
			}
			await page.waitForTimeout(600);
			await freezeAnimations(page);

			const mockupRoot = page.locator("#storybook-root");
			const mockupBox = await mockupRoot.boundingBox();
			let mockupShot: Buffer;
			if (mockupBox && mockupBox.height > 0) {
				mockupShot = (await mockupRoot.screenshot()) as Buffer;
			} else {
				mockupShot = (await page.screenshot()) as Buffer;
			}

			// 2. Screenshot the Storybook story
			const storyPage = await context.newPage();
			await storyPage.goto(`/iframe.html?id=${pair.storyId}&viewMode=story`, {
				waitUntil: "domcontentloaded",
			});
			await storyPage.waitForTimeout(800);
			await freezeAnimations(storyPage);

			const storyRoot = storyPage.locator("#storybook-root");
			const storyBox = await storyRoot.boundingBox();
			let storyShot: Buffer;
			if (storyBox && storyBox.height > 0) {
				storyShot = (await storyRoot.screenshot()) as Buffer;
			} else {
				storyShot = (await storyPage.screenshot()) as Buffer;
			}
			await storyPage.close();

			// 3. Compare
			const result = compareImages(mockupShot, storyShot);
			const maxDiff = pair.maxDiff ?? MAX_DIFF_RATIO;

			// Save debug images for every run
			const safeName = pair.name.replace(/[^a-zA-Z0-9]/g, "-");
			saveDebugImage(`${safeName}-mockup.png`, mockupShot);
			saveDebugImage(`${safeName}-story.png`, storyShot);
			if (result.diffCount > 0) {
				saveDebugImage(`${safeName}-diff.png`, result.diffImage);
			}

			console.log(
				`[fidelity] ${pair.name}: ${result.diffCount} pixels (${(result.diffRatio * 100).toFixed(1)}%)`,
			);

			expect(
				result.diffRatio,
				`${pair.name}: ${(result.diffRatio * 100).toFixed(1)}% pixels differ (max ${(maxDiff * 100).toFixed(0)}%). See test-debug/fidelity/${safeName}-diff.png`,
			).toBeLessThanOrEqual(maxDiff);
		});
	}
});
